app/forms/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, PasswordField, validators
from wtforms import StringField, SubmitField, SelectField, FileField, validators

class FormMusic(FlaskForm):
    name = StringField('Nome:', [validators.DataRequired(),
                                validators.length(min=2, max=30)])
    artist = StringField('Artista:', [validators.DataRequired(),
                                     validators.length(min=2, max=50)])
    
    artist = StringField('Artista:', [validators.DataRequired(),
                                     validators.length(min=2, max=50)])
    
    genre = SelectField('Gênero:',
                        validators=[validators.DataRequired(message="Por favor, escolha um gênero.")],
                        choices=[
                            ('', 'Escolha...'),
                            ('Arrocha', 'Arrocha'),
                            ('Samba', 'Samba'),
                            ('Pop', 'Pop'),
                            ('Funk', 'Funk'),
                            ('Sertanejo', 'Sertanejo'),
                            ('Rock', 'Rock'),
                            ('MBP', 'MBP')
                            ]
                        )

    button = SubmitField('Cadastrar')

class FormLogin(FlaskForm):
    login = StringField('Login:', [validators.DataRequired(),
                        validators.length(min=6, max=20)])
    password = PasswordField('Senha:', [validators.DataRequired(),
                             validators.length(min=4, max=15)])
    button = SubmitField('Entrar')

class FormRegister(FlaskForm):
    name = StringField('Nome completo:', [validators.DataRequired(),
                        validators.length(min=2, max=50)])
    login = StringField('Login:', [validators.DataRequired(),
                        validators.length(min=6, max=20)])
    password = PasswordField('Senha:', [validators.DataRequired(),
                             validators.length(min=4, max=30)])
    button = SubmitField('Cadastrar')

app/controllers/controller.py
from flask import render_template, Blueprint, session, redirect, url_for, flash

from app.domain.music.model import Music
from app.domain.upload.services import search_image
from app.forms.forms import FormMusic, FormLogin, FormRegister
from app.forms.forms import FormMusic

# Esse controlador serve apenas para renderizar as páginas:

index_bp = Blueprint('index_bp', __name__)

@index_bp.route('/')
def index():
    if session['username'] == None or 'username' not in session:
        flash("É necessário se autenticar!")
        return redirect(url_for('index_bp.login_page'))
    return render_template("index.html",
                           title = "Início")

@index_bp.route('/add')
def add_page():
    form = FormMusic()
    if session['username'] == None or 'username' not in session:
        flash("É necessário se autenticar!")
        return redirect(url_for('index_bp.login_page'))
    return render_template("add_page.html", 
                           form=form,
                           title = "Cadastrar música")

@index_bp.route('/musics')
def list_page():
    if session['username'] == None or 'username' not in session:
        flash("É necessário se autenticar!")
        return redirect(url_for('index_bp.login_page'))
    
    lista = Music.query.order_by(Music.id)

    return render_template("list_page.html",
                           musics = lista,
                           title = "Lista de músicas")

@index_bp.route('/update/<int:id>')
def update_page(id):
    if session['username'] == None or 'username' not in session:
        flash("É necessário se autenticar!")
        return redirect(url_for('index_bp.login_page'))
    
    find_music = Music.query.filter_by(id=id).first()

    form = FormMusic()

    form.name.data = find_music.name
    form.artist.data = find_music.artist
    form.genre.data = find_music.genre

    album = search_image(id)

    return render_template('update_page.html', 
                           title = "Editar música",
                           form = form,
                           music = form,
                           album_music = album,
                           id=id)

@index_bp.route('/login')
def login_page():
    form = FormLogin()
    return render_template("auth/login_page.html",
                           title = "Login",
                           form=form)

@index_bp.route('/register')
def register_page():
    form = FormRegister()
    return render_template("auth/register_page.html",
                           title = "Registre-se",
                           form=form)

app/controllers/music_controller.py
from flask import redirect, request, Blueprint, url_for, flash, send_from_directory

from app.domain.music.model import Music
from app.db.config import db
from app.forms.forms import FormMusic

from app.domain.upload import config
from app.domain.upload.services import delete_image
from app.forms.forms import FormMusic
 
# Esse controlador realiza ações e também pode redirecionar para outras páginas:

music_bp = Blueprint('music_bp', __name__)

@music_bp.route('/add', methods=['POST'])
def add_music():

    form_recivied = FormMusic(request.form)

    if not form_recivied.validate_on_submit():
        return redirect(url_for('index_bp.register_page'))

    form_name = form_recivied.name.data
    form_artist = form_recivied.artist.data
    form_genre = form_recivied.genre.data

    form_recivied = FormMusic(request.form)

    if not form_recivied.validate_on_submit():
        return redirect(url_for('index_bp.add_page'))

    form_name = form_recivied.name.data
    form_artist = form_recivied.artist.data
    form_genre = form_recivied.genre.data

    music = Music.query.filter_by(name=form_name).first()
    
    if music:
        flash("Música já cadastrada!")
        return redirect(url_for('index_bp.list_page'))
    
    new_music = Music(name=form_name,
                      artist=form_artist, 
                      genre=form_genre)
    
    db.session.add(new_music)
    db.session.commit()

    archive = request.files['inputFile']

    if archive:    
        archive_name = archive.filename
        archive_name = archive_name.split('.')
        extension = archive_name[len(archive_name)-1]
        folder = config.UPLOAD_FOLDER
        archive.save(f'{folder}album{new_music.id}.{extension}')

    return redirect(url_for('index_bp.list_page'))

@music_bp.route('/update', methods=['POST'])
def update_music():
    
    form_recivied = FormMusic(request.form)

    if form_recivied.validate_on_submit():

        music = Music.query.filter_by(id=request.form['inputId']).first()
        
        music.name = form_recivied.name.data
        music.artist = form_recivied.artist.data
        music.genre = form_recivied.genre.data

        db.session.add(music)
        db.session.commit()

        archive = request.files['inputFile']

        if archive:
            archive_name = archive.filename
            archive_name = archive_name.split('.')
            extension = archive_name[len(archive_name)-1]
            folder = config.UPLOAD_FOLDER
            delete_image(music.id)
            archive.save(f'{folder}album{music.id}.{extension}')

        flash("Música editada com sucesso!")

    return redirect(url_for('index_bp.list_page'))

@music_bp.route('/delete/<int:id>')
def delete_music(id):

    Music.query.filter_by(id=id).delete()
    flash("Música excluída com sucesso!")

    delete_image(id)

    db.session.commit()

    return redirect(url_for('index_bp.list_page'))

@music_bp.route('/uploads/<name_image>')
def show_image(name_image):
    return send_from_directory('uploads', name_image)

app/main.py
from flask import Flask
from dotenv import load_dotenv
import os

from app.db.config import db, DB_URL
from app.controllers.music_controller import music_bp
from app.controllers.controller import index_bp
from app.controllers.auth.auth_controller import auth_bp

load_dotenv()

app = Flask(__name__)
app.secret_key = os.getenv('SECRET_KEY')

app.config['SQLALCHEMY_DATABASE_URI'] = DB_URL
db.init_app(app)

app.register_blueprint(index_bp)
app.register_blueprint(music_bp)
app.register_blueprint(auth_bp)

if __name__ == '__main__':
    app.run(debug=True)

app/templates/add_page.html
{% extends 'auth/template_login.html' %}

{% block content %}
<div class="container">
    <form method="post" action="{{ url_for('music_bp.add_music') }}" enctype="multipart/form-data">
        <fieldset>

            {{ form.csrf_token() }}

            <div class="row mb-3">
                {{ form.name.label(class='form-label') }}
                {{ form.name(class='form-control') }}
            </div>

            <div class="row mb-3">
                {{ form.artist.label(class='form-label') }}
                {{ form.artist(class='form-control') }}
            </div>

            <div class="row mb-3">
                {{ form.genre.label(class='form-label') }}
                {{ form.genre(class='form-control') }}
            </div>

            <div class="row mb-3">
                <label for="inputFile">Selecione a capa do album':</label>
                <input type="file" class="form-control" name="inputFile" 
                id="inputFile" accept=".jpg, .jpeg, .png">
            </div>

            <div class="row">
                {{ form.button(class='btn btn-primary') }}
            </div>
        </fieldset>
    </form>
</div>
{% endblock content %}

app/templates/index.html
{% extends "auth/template_login.html" %}

{% block content %}

{% endblock content %}

app/templates/list_page.html
{% extends 'auth/template_login.html' %}

{% block content %}

<table class="table table-hover">
    <thead class="table-dark">
        <tr>
            <th scope="col">Música</th>
            <th scope="col">Artista(s)</th>
            <th scope="col">Gênero</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>

    <tbody>
        {% for music in musics %}
            <tr>
                <td>{{ music.name }}</td>
                <td>{{ music.artist }}</td>
                <td>{{ music.genre }}</td>
                <td>
                    <a style="color: rgb(61, 61, 61); text-decoration: none;" 
                    class="p-1" href="{{ url_for('index_bp.update_page', id=music.id) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"/>
                        </svg>
                    </a>
                    
                    <a style="color: rgb(253, 60, 60); text-decoration: none;" 
                    class="p-1" href="{{ url_for('music_bp.delete_music', id=music.id) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                        </svg>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

app/templates/register_page.html
{% extends 'template.html' %}

{% block content %}
<div class="container">
    <form method="post" action="{{ url_for('music_bp.add_music') }}" enctype="multipart/form-data">
        <fieldset>

            {{ form.csrf_token() }}

            <div class="row mb-3">
                {{ form.name.label(class='form-label') }}
                {{ form.name(class='form-control') }}
            </div>

            <div class="row mb-3">
                {{ form.artist.label(class='form-label') }}
                {{ form.artist(class='form-control') }}
            </div>

            <div class="row mb-3">
                {{ form.genre.label(class='form-label') }}
                {{ form.genre(class='form-control') }}
            </div>

            <div class="row mb-3">
                <label for="inputFile">Selecione a capa do album':</label>
                <input type="file" class="form-control" name="inputFile" 
                id="inputFile" accept=".jpg, .jpeg, .png">
            </div>

            <div class="row">
                {{ form.button(class='btn btn-primary') }}
            </div>
        </fieldset>
    </form>
</div>
{% endblock content %}

app/templates/template.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>

    <link rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
    crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">iMusic</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ms-auto">
                    <a class="nav-link" href="{{ url_for('index_bp.register_page') }}">Registre-se</a>
                    <a class="nav-link" href="{{ url_for('index_bp.login_page') }}">Login</a>
                </div>
            </div>
        </div>
    </nav>
    
    <div class="container">

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <ul class=list-unstyled id="messages">
                {% for category, message in messages %}
                    <li class="alert alert-primary mt-4">{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endwith %}

        <h2>{{ title }}</h2>
        {% block content%}
        {% endblock content%}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
    </script>    
</body>
</html>

app/templates/update_page.html
{% extends 'auth/template_login.html' %}

{% block content %}
<div class="container">
    <form method="post" action="{{ url_for('music_bp.update_music') }}" enctype="multipart/form-data">
        <fieldset> 
            
            {{ form.csrf_token() }}

            <input type="hidden" name="inputId" value="{{id}}">
            
            <figure class="img-thmbnail mb-3">
                <img class="img-fluid" src="{{ url_for('music_bp.show_image', name_image=album_music) }}">
            
                <figcaption>
                    <label for="inputFile">
                        Altere a capa do album:
                        <input type="file" class="form-control" name="inputFile" 
                        id="inputFile" accept=".jpg, .jpeg, .png">
                    </label>
                </figcaption>
            </figure>


            <div class="row mb-3">
                {{ form.name.label(class='form-label') }}
                {{ form.name(class='form-control') }}
            </div>

            <div class="row mb-3">
                {{ form.artist.label(class='form-label') }}
                {{ form.artist(class='form-control') }}
            </div>

            <div class="row mb-3">
                {{ form.genre.label(class='form-label') }}
                {{ form.genre(class='form-control') }}
            </div>

            <div class="row">
                {{ form.button(class='btn btn-primary') }}
            </div>

        </fieldset>
    </form>
</div>
{% endblock content %}